version: "3"

services:

# API
  api:
    image: mjsasha/impinfapi:2.0.2
    container_name: api
    restart: always
    depends_on:
        - imp-inf-db
    ports:
      - "8080:80"

# Database
  imp-inf-db:
    image: mysql
    container_name: imp-inf-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: imp-inf-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin

# Database adminer
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "5000:8080"