version: "3"

# Эта штука разворачивает весь проект
services:

# BackEnd
  backend:
    image: mjsasha/backend_important-information:2.5
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=imp-inf-db
      - PSQL_HOST=imp-inf-db
      - PSQL_PORT=5432
      - PSQL_USER=postgres
      - PSQL_PASSWORD=postgres

# FrontEnd
  frontend:
    image: mjsasha/frontend_important-information:1.0
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"

# База данных
  postgres:
    image: postgres:14.2
    container_name: imp-inf-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=imp-inf-db

# Админка
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root